sample_payload: 'sample_payload.json'
EXPT_DIR : "./outputs"
DATA_DIR : "./data"
MODEL_DIRECTORY : "./models"
OUTPUT_DIRECTORY: './ckpts'
IMG_DIRECTORY : "/home/ubuntu/AlectioSDK/examples/image_classification/Deepweeds/data/images"
LABEL_DIRECTORY : "/home/ubuntu/AlectioSDK/examples/image_classification/Deepweeds/data/labels"
WEIGHTS_DIR : "./models"
exp_name: "Deepweeds"



### TRAIN FUNCTION ARGS ###
train_epochs: 5
batch_size: 8
RAW_IMG_SIZE : (256, 256)
IMG_SIZE : (224, 224)
INPUT_SHAPE : (IMG_SIZE[0], IMG_SIZE[1], 3)
MAX_EPOCH : 2
BATCH_SIZE: 32
FOLDS : [1]
STOPPING_PATIENCE : 32
LR_PATIENCE : 16
INITIAL_LR : 0.0001
CLASSES : [0, 1, 2, 3, 4, 5, 6, 7, 8]
CLASSES_STR : ['0', '1', '2', '3', '4', '5', '6', '7','8']
MODELNAME: resnet                                                       #### support for [resnet, inception]
